import {ScheduleTableItem} from "@/features/courseSchedule/type/schedule.ts";

export const defaultItems: ScheduleTableItem[] = [
    {
        id: "demo-1",
        week: 1,
        day: 1,
        begin: 1,
        end: 4,
        title: "程序设计基础",
        location: "西综合308",
        teacher: "王大牛",
    },
    {
        id: "demo-2",
        week: 1,
        day: 1,
        begin: 5,
        end: 6,
        title: "高等数学",
        location: "6A-102",
        teacher: "张",
        status: 4,
    },
    {
        id: "demo-3",
        week: 1,
        day: 1,
        begin: 9,
        end: 11,
        title: "大学生心理健康",
        location: "网络教室",
        teacher: "网络教师",
    },

    {
        id: "demo-4",
        week: 1,
        day: 2,
        begin: 1,
        end: 2,
        title: "大学英语（一）",
        location: "外语楼B205",
        teacher: "李老师",
        kind: "course",
        isShift: true,
    },
    {id: "demo-5", week: 1, day: 2, begin: 3, end: 4, title: "羽毛球", location: "西羽毛球", teacher: "教练组"},
    {
        id: "demo-6",
        week: 1,
        day: 2,
        begin: 7,
        end: 8,
        title: "线性代数",
        location: "6A-203",
        teacher: "赵老师",
        kind: "course",
    },

    // 周四：全天空
    {
        id: "demo-10",
        week: 1,
        day: 4,
        begin: 3,
        end: 4,
        title: "马克思主义基本原理",
        location: "西3-408",
        teacher: "刘教授",
        kind: "course",
        status: 1,
    },
    {
        id: "demo-11",
        week: 1,
        day: 4,
        begin: 5,
        end: 6,
        title: "数据结构",
        location: "机房B202",
        teacher: "陈老师",
        kind: "course",
        status: 2,
    },
    {
        id: "demo-12",
        week: 1,
        day: 4,
        begin: 9,
        end: 10,
        title: "音乐鉴赏",
        location: "艺术楼",
        teacher: "网络教师",
        kind: "course",
    },

    // ========== 节假日（第4周清明节） ==========
    {
        id: "demo-holiday",
        week: 1,
        day: 5,
        begin: 1,
        end: 13,
        title: "示例假期",
        subtitle: "放假",
        location: "",
        teacher: "",
        kind: "holiday",
    },

    // ========== 考试（第8周期中） ==========
    {
        id: "demo-exam-1",
        week: 1,
        day: 3,
        begin: 1,
        end: 3,
        title: "线性代数",
        location: "6A-623",
        kind: "exam",
        color: "#ff4d4f",
        seat: "45",
    },
    {
        id: "demo-exam-2",
        week: 1,
        day: 3,
        begin: 5,
        end: 7,
        title: "大学英语（一）",
        location: "西综合310",
        kind: "exam",
        color: "#ff4d4f",
        seat: "20",
    },
];
