export interface TeachBuildingFloor{
    id:string;
    name:string;
    image:any;
}

export interface TeachBuilding{
    id:string;
    name:string;
    floors:TeachBuildingFloor[];
}

export const TeachBuildingList:TeachBuilding[]=[
    {
        id:"erjiao",
        name:"第二教学楼",
        floors:[
            {
                id:"1",
                name:"1层楼层图",
                image:require("@/pictures/erjiao/2-1.jpg"),
            },
            {
                id:"2-4",
                name:"2~4层楼层图",
                image:require("@/pictures/erjiao/2-2~4.jpg"),
            },
            {
                id:"5-6",
                name:"5~6层楼层图",
                image:require("@/pictures/erjiao/2-5~6.jpg"),
            },
            {
                id:"7",
                name:"7层楼层图",
                image:require("@/pictures/erjiao/2-7.jpg"),
            },
        ]
    },
    {
        id:"sanjiao",
        name:"第三教学楼",
        floors:[
            {
                id:"1",
                name:"1~2层楼层图",
                image:require("@/pictures/sanjiao/3-1~2.jpg"),
            },
            {
                id:"3-6",
                name:"3~6层楼层图",
                image:require("@/pictures/sanjiao/3-3~6.jpg"),
            },
            {
                id:"7",
                name:"7层楼层图",
                image:require("@/pictures/sanjiao/3-7.jpg"),
            }
        ]
    },
    {
        id: "liujiao",
        name: "第六教学楼",
        floors:[
            {
                id:"all",
                name:"总楼层图",
                image:require("@/pictures/liujiao/all.jpeg"),
            },
            {
                id:"1",
                name:"1楼",
                image:require("@/pictures/liujiao/1.jpeg"),
            },
            {
                id:"2",
                name:"2楼",
                image:require("@/pictures/liujiao/2.jpeg"),
            },
            {
                id:"3",
                name:"3楼",
                image:require("@/pictures/liujiao/3.jpeg"),
            },
            {
                id:"4",
                name:"4楼",
                image:require("@/pictures/liujiao/4.jpeg"),
            },
            {
                id:"5",
                name:"5楼",
                image:require("@/pictures/liujiao/5.jpeg"),
            },
            {
                id:"6",
                name:"6楼",
                image:require("@/pictures/liujiao/6.jpeg"),
            },
        ],
    },
    {
        id:"shijiao",
        name:"第十教学楼",
        floors:[
            {
                id:"A1",
                name:"A区1层",
                image:require("@/pictures/shijiao/A1.jpeg"),
            },
            {
                id:"A2",
                name:"A区2层",
                image:require("@/pictures/shijiao/A2.jpeg"),
            },
            {
                id:"B23",
                name:"B区2~3平面图",
                image:require("@/pictures/shijiao/10B-2_3.png"),
            },
            {
                id:"B46",
                name:"B区4~6平面图",
                image:require("@/pictures/shijiao/10B-4_6.png"),
            },
        ]
    },
];
